// Simulates realistic Tivly meeting - longer with numbers and metrics
export const simulateMeetingAudio = (onTranscript: (text: string, isFinal: boolean) => void) => {
  const meetingScript = [
    { text: "God", delay: 0 },
    { text: "morgon", delay: 20 },
    { text: "alla", delay: 15 },
    { text: "och", delay: 10 },
    { text: "välkomna", delay: 20 },
    { text: "till", delay: 10 },
    { text: "vårt", delay: 15 },
    { text: "veckomöte.", delay: 25, final: true },
    
    { text: "Idag", delay: 30 },
    { text: "är", delay: 10 },
    { text: "det", delay: 10 },
    { text: "den", delay: 10 },
    { text: "femtonde", delay: 20 },
    { text: "januari", delay: 20 },
    { text: "och", delay: 10 },
    { text: "vi", delay: 10 },
    { text: "ska", delay: 10 },
    { text: "diskutera", delay: 20 },
    { text: "Tivly,", delay: 25 },
    { text: "vår", delay: 15 },
    { text: "mötesprotokollsapp.", delay: 30, final: true },
    
    { text: "Vi", delay: 30 },
    { text: "har", delay: 10 },
    { text: "tre", delay: 15 },
    { text: "viktiga", delay: 20 },
    { text: "punkter", delay: 20 },
    { text: "på", delay: 10 },
    { text: "agendan", delay: 20 },
    { text: "idag.", delay: 25, final: true },
    
    { text: "Maria,", delay: 30 },
    { text: "kan", delay: 15 },
    { text: "du", delay: 10 },
    { text: "berätta", delay: 20 },
    { text: "om", delay: 10 },
    { text: "produktstatusen?", delay: 30, final: true },
    
    { text: "Absolut.", delay: 35, final: true },
    { text: "Tivly", delay: 25 },
    { text: "har", delay: 10 },
    { text: "nu", delay: 10 },
    { text: "exakt", delay: 20 },
    { text: "femhundratvåtio", delay: 40 },
    { text: "aktiva", delay: 20 },
    { text: "användare", delay: 25 },
    { text: "sedan", delay: 15 },
    { text: "beta-lanseringen", delay: 35 },
    { text: "den", delay: 10 },
    { text: "första", delay: 20 },
    { text: "november.", delay: 25, final: true },
    
    { text: "Det", delay: 30 },
    { text: "är", delay: 10 },
    { text: "en", delay: 10 },
    { text: "ökning", delay: 20 },
    { text: "med", delay: 10 },
    { text: "tjugotre", delay: 25 },
    { text: "procent", delay: 20 },
    { text: "sedan", delay: 15 },
    { text: "förra", delay: 15 },
    { text: "veckan.", delay: 25, final: true },
    
    { text: "Genomsnittet", delay: 35 },
    { text: "ligger", delay: 20 },
    { text: "på", delay: 10 },
    { text: "åtta", delay: 15 },
    { text: "komma", delay: 15 },
    { text: "tre", delay: 15 },
    { text: "protokoll", delay: 20 },
    { text: "per", delay: 10 },
    { text: "användare", delay: 20 },
    { text: "och", delay: 10 },
    { text: "månad.", delay: 25, final: true },
    
    { text: "Våra", delay: 30 },
    { text: "topp", delay: 15 },
    { text: "fem", delay: 15 },
    { text: "kunder", delay: 20 },
    { text: "skapar", delay: 20 },
    { text: "mellan", delay: 20 },
    { text: "trettio", delay: 25 },
    { text: "och", delay: 10 },
    { text: "femtio", delay: 20 },
    { text: "möten", delay: 15 },
    { text: "per", delay: 10 },
    { text: "månad.", delay: 25, final: true },
    
    { text: "AI-funktionen", delay: 35 },
    { text: "för", delay: 10 },
    { text: "automatisk", delay: 25 },
    { text: "sammanfattning", delay: 30 },
    { text: "används", delay: 20 },
    { text: "i", delay: 8 },
    { text: "nittioen", delay: 25 },
    { text: "komma", delay: 15 },
    { text: "sex", delay: 15 },
    { text: "procent", delay: 20 },
    { text: "av", delay: 10 },
    { text: "alla", delay: 15 },
    { text: "möten.", delay: 25, final: true },
    
    { text: "Användarna", delay: 35 },
    { text: "är", delay: 10 },
    { text: "mycket", delay: 15 },
    { text: "nöjda", delay: 15 },
    { text: "med", delay: 10 },
    { text: "en", delay: 10 },
    { text: "NPS-poäng", delay: 30 },
    { text: "på", delay: 10 },
    { text: "sjuttiotvå.", delay: 30, final: true },
    
    { text: "Vi", delay: 30 },
    { text: "har", delay: 10 },
    { text: "dock", delay: 15 },
    { text: "fått", delay: 15 },
    { text: "tretton", delay: 25 },
    { text: "klagomål", delay: 25 },
    { text: "om", delay: 10 },
    { text: "att", delay: 10 },
    { text: "transkriberingen", delay: 35 },
    { text: "tar", delay: 10 },
    { text: "för", delay: 10 },
    { text: "lång", delay: 15 },
    { text: "tid", delay: 10 },
    { text: "vid", delay: 10 },
    { text: "möten", delay: 15 },
    { text: "över", delay: 15 },
    { text: "fyrtio", delay: 20 },
    { text: "minuter.", delay: 25, final: true },
    
    { text: "Bra", delay: 35 },
    { text: "Maria.", delay: 25, final: true },
    
    { text: "Erik,", delay: 30 },
    { text: "vad", delay: 15 },
    { text: "säger", delay: 15 },
    { text: "det", delay: 10 },
    { text: "tekniska", delay: 20 },
    { text: "teamet?", delay: 25, final: true },
    
    { text: "Jo,", delay: 35, final: true },
    { text: "vi", delay: 15 },
    { text: "har", delay: 10 },
    { text: "identifierat", delay: 30 },
    { text: "problemet.", delay: 30, final: true },
    
    { text: "Just", delay: 30 },
    { text: "nu", delay: 10 },
    { text: "tar", delay: 10 },
    { text: "det", delay: 10 },
    { text: "i", delay: 8 },
    { text: "genomsnitt", delay: 25 },
    { text: "fyra", delay: 15 },
    { text: "komma", delay: 15 },
    { text: "åtta", delay: 15 },
    { text: "minuter", delay: 20 },
    { text: "att", delay: 10 },
    { text: "transkribera", delay: 30 },
    { text: "en", delay: 10 },
    { text: "timmes", delay: 20 },
    { text: "möte.", delay: 25, final: true },
    
    { text: "Vi", delay: 30 },
    { text: "planerar", delay: 20 },
    { text: "att", delay: 10 },
    { text: "implementera", delay: 30 },
    { text: "chunked", delay: 20 },
    { text: "processing", delay: 25 },
    { text: "nästa", delay: 15 },
    { text: "vecka.", delay: 25, final: true },
    
    { text: "Det", delay: 30 },
    { text: "borde", delay: 15 },
    { text: "minska", delay: 20 },
    { text: "tiden", delay: 15 },
    { text: "till", delay: 10 },
    { text: "ungefär", delay: 20 },
    { text: "en", delay: 10 },
    { text: "komma", delay: 15 },
    { text: "nio", delay: 15 },
    { text: "minuter.", delay: 25, final: true },
    
    { text: "Det", delay: 30 },
    { text: "är", delay: 10 },
    { text: "en", delay: 10 },
    { text: "förbättring", delay: 25 },
    { text: "på", delay: 10 },
    { text: "sextio", delay: 20 },
    { text: "procent.", delay: 25, final: true },
    
    { text: "Vi", delay: 30 },
    { text: "testar", delay: 15 },
    { text: "också", delay: 15 },
    { text: "Gemini", delay: 20 },
    { text: "två", delay: 15 },
    { text: "punkt", delay: 15 },
    { text: "noll", delay: 15 },
    { text: "Flash", delay: 20 },
    { text: "som", delay: 10 },
    { text: "är", delay: 8 },
    { text: "trettio", delay: 20 },
    { text: "procent", delay: 20 },
    { text: "snabbare.", delay: 25, final: true },
    
    { text: "Budget", delay: 35 },
    { text: "för", delay: 10 },
    { text: "detta", delay: 15 },
    { text: "är", delay: 10 },
    { text: "tjugofemtusen", delay: 35 },
    { text: "kronor.", delay: 25, final: true },
    
    { text: "Utmärkt!", delay: 35, final: true },
    
    { text: "Johan,", delay: 30 },
    { text: "kan", delay: 15 },
    { text: "du", delay: 10 },
    { text: "dela", delay: 15 },
    { text: "affärsplanen?", delay: 30, final: true },
    
    { text: "Självklart.", delay: 35, final: true },
    
    { text: "Vi", delay: 25 },
    { text: "föreslår", delay: 20 },
    { text: "tre", delay: 15 },
    { text: "prenumerationsnivåer.", delay: 45, final: true },
    
    { text: "Basic", delay: 30 },
    { text: "för", delay: 10 },
    { text: "nittionio", delay: 25 },
    { text: "kronor", delay: 20 },
    { text: "per", delay: 10 },
    { text: "månad", delay: 15 },
    { text: "ger", delay: 10 },
    { text: "upp", delay: 10 },
    { text: "till", delay: 10 },
    { text: "tio", delay: 15 },
    { text: "möten.", delay: 25, final: true },
    
    { text: "Pro", delay: 30 },
    { text: "för", delay: 10 },
    { text: "tvåhundranittionio", delay: 45 },
    { text: "kronor", delay: 20 },
    { text: "ger", delay: 10 },
    { text: "obegränsat", delay: 30 },
    { text: "antal", delay: 15 },
    { text: "möten", delay: 15 },
    { text: "plus", delay: 15 },
    { text: "alla", delay: 15 },
    { text: "integrationer.", delay: 35, final: true },
    
    { text: "Enterprise", delay: 35 },
    { text: "börjar", delay: 20 },
    { text: "på", delay: 10 },
    { text: "niohundranittionio", delay: 45 },
    { text: "kronor", delay: 20 },
    { text: "per", delay: 10 },
    { text: "månad.", delay: 25, final: true },
    
    { text: "Våra", delay: 30 },
    { text: "konkurrenter", delay: 30 },
    { text: "tar", delay: 10 },
    { text: "mellan", delay: 20 },
    { text: "trehundra", delay: 25 },
    { text: "och", delay: 10 },
    { text: "femhundra", delay: 25 },
    { text: "kronor", delay: 20 },
    { text: "för", delay: 10 },
    { text: "liknande", delay: 20 },
    { text: "funktioner.", delay: 30, final: true },
    
    { text: "Baserat", delay: 30 },
    { text: "på", delay: 8 },
    { text: "en", delay: 10 },
    { text: "konverteringsgrad", delay: 40 },
    { text: "på", delay: 10 },
    { text: "tolv", delay: 15 },
    { text: "procent", delay: 20 },
    { text: "kan", delay: 10 },
    { text: "vi", delay: 8 },
    { text: "uppnå", delay: 18 },
    { text: "lönsamhet", delay: 28 },
    { text: "vid", delay: 10 },
    { text: "tvåtusen", delay: 25 },
    { text: "betalande", delay: 25 },
    { text: "kunder.", delay: 25, final: true },
    
    { text: "Det", delay: 30 },
    { text: "skulle", delay: 15 },
    { text: "ge", delay: 10 },
    { text: "oss", delay: 10 },
    { text: "en", delay: 10 },
    { text: "årlig", delay: 15 },
    { text: "omsättning", delay: 28 },
    { text: "på", delay: 8 },
    { text: "cirka", delay: 15 },
    { text: "sex", delay: 15 },
    { text: "komma", delay: 15 },
    { text: "nio", delay: 15 },
    { text: "miljoner", delay: 25 },
    { text: "kronor.", delay: 25, final: true },
    
    { text: "Med", delay: 30 },
    { text: "en", delay: 10 },
    { text: "bruttomarginal", delay: 35 },
    { text: "på", delay: 8 },
    { text: "åttiofem", delay: 25 },
    { text: "procent", delay: 20 },
    { text: "blir", delay: 12 },
    { text: "det", delay: 10 },
    { text: "fem", delay: 15 },
    { text: "komma", delay: 15 },
    { text: "nio", delay: 15 },
    { text: "miljoner", delay: 25 },
    { text: "i", delay: 8 },
    { text: "bruttovinst.", delay: 30, final: true },
    
    { text: "Fantastiskt!", delay: 35, final: true },
    
    { text: "Låt", delay: 30 },
    { text: "oss", delay: 10 },
    { text: "sammanfatta.", delay: 30, final: true },
    
    { text: "Erik", delay: 30 },
    { text: "implementerar", delay: 35 },
    { text: "chunked", delay: 20 },
    { text: "processing", delay: 25 },
    { text: "till", delay: 10 },
    { text: "den", delay: 10 },
    { text: "tjugoandra", delay: 30 },
    { text: "januari.", delay: 25, final: true },
    
    { text: "Budget", delay: 30 },
    { text: "tjugofemtusen", delay: 35 },
    { text: "kronor", delay: 20 },
    { text: "godkänd.", delay: 25, final: true },
    
    { text: "Johan", delay: 30 },
    { text: "färdigställer", delay: 30 },
    { text: "prissättningsstrategin", delay: 50 },
    { text: "till", delay: 10 },
    { text: "nästa", delay: 15 },
    { text: "fredag.", delay: 25, final: true },
    
    { text: "Vi", delay: 30 },
    { text: "siktar", delay: 15 },
    { text: "på", delay: 8 },
    { text: "offentlig", delay: 28 },
    { text: "lansering", delay: 25 },
    { text: "den", delay: 10 },
    { text: "första", delay: 18 },
    { text: "mars", delay: 15 },
    { text: "klockan", delay: 20 },
    { text: "nio.", delay: 20, final: true },
    
    { text: "Nästa", delay: 30 },
    { text: "möte", delay: 15 },
    { text: "den", delay: 10 },
    { text: "tjugoandra", delay: 30 },
    { text: "januari", delay: 20 },
    { text: "klockan", delay: 20 },
    { text: "tio.", delay: 20, final: true },
    
    { text: "Tack", delay: 30 },
    { text: "alla", delay: 15 },
    { text: "för", delay: 10 },
    { text: "idag,", delay: 20 },
    { text: "bra", delay: 15 },
    { text: "jobbat!", delay: 25, final: true },
  ];

  let currentIndex = 0;
  let currentSentence = "";
  const timeouts: NodeJS.Timeout[] = [];

  const scheduleNext = () => {
    if (currentIndex >= meetingScript.length) return;
    const item = meetingScript[currentIndex++];
    const timeout = setTimeout(() => {
      if (item.final) {
        currentSentence += " " + item.text;
        onTranscript(currentSentence.trim(), true);
        currentSentence = "";
      } else {
        currentSentence += " " + item.text;
        onTranscript(currentSentence.trim(), false);
      }
      scheduleNext();
    }, item.delay);
    timeouts.push(timeout);
  };

  scheduleNext();
  return () => timeouts.forEach(t => clearTimeout(t));
};